version: '3.3'

services:
  redis-master:
    image: ascent/redis-sentinel
    build: ../
    environment:
        - START_COMMAND=sh /redis/redis-wrapper.sh
        - VAULT_ADDR=http://vault:8200
        - VAULT_TOKEN=vaultroot
    networks:
      - ascentnet
  # Slave
  redis-slave:
    image: ascent/redis-sentinel
    build: ../
    environment:
        - START_COMMAND=sh /redis/redis-wrapper.sh --slaveof redis-master 6379
        - VAULT_ADDR=http://vault:8200
        - VAULT_TOKEN=vaultroot
    networks:
      - ascentnet
  redis-sentinel:
    image: ascent/redis-sentinel
    build: ../
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    networks:
      - ascentnet
  redis-sentinel2:
    image: ascent/redis-sentinel
    build: ../
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    networks:
      - ascentnet
  redis-sentinel3:
    image: ascent/redis-sentinel
    build: ../
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    networks:
      - ascentnet
networks:
  ascentnet:
    driver: bridge
