version: "3"
# Make sure to start vault container before running
services:
  sonarqube:
    image: ascent/ascent-sonarqube
    build: ../../sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&amp;characterEncoding=utf8
      - SONARQUBE_JDBC_USER=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - BASE_URL=http://127.0.0.1:9000
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    hostname: db
    image: ascent/ascent-sonar-db
    build: ../../sonarqube/database
    volumes:
      - /var/log/mysql
      - /var/lib/mysql
    command:
      - '--user=mysql --pxc-strict-mode=PERMISSIVE'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sonar
      - CLUSTER_NAME=sonarcluster
      - MYSQL_ROOT_PASSWORD=defaultpassword
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
    networks:
      - sonarnet
networks:
  sonarnet:
    driver: bridge
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
