version: "3.3"
services:
    #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
    elasticsearch:
        image: ascent/ascent-elasticsearch
        build:
            context: ../../elasticsearch
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - REPLICA_AMOUNT=1
            - MIN_MASTER_NODES=1
            - SECURE_CONNECT=false
            - VAULT_TOKEN=vaultroot
            - VAULT_ADDR=http://vault:8200
        ports:
            - 9200:9200
        networks:
            logging:
                aliases:
                    - elastic.internal.vets-api.gov
            ascentnet:
                aliases:
                    - elastic.internal.vets-api.gov
        ulimits:
            nproc: 655350
            nofile: 655350
            memlock:
                soft: -1
                hard: -1
networks:
  logging:
    driver: bridge
  ascentnet:
    driver: bridge
