## S3 and SQS Configurations for Ascent   
#ascent:
#  aws:
#    access_key_id: ${AWS_ACCESS_KEY}
#    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
#  s3:
#    bucket: ${AWS_S3_BUCKET_NAME}
#    region: ${AWS_REGION:us-east-1}
#    uploadfile: classpath:ascent-s3-upload-file.txt
#    key: ascent-s3-upload-file.txt
#  sqs:
#    region: ${AWS_SQS_REGION:us-east-1}
#    endpoint: ${AWS_SQS_ENDPOINT}
#    numberOfMessagesToPrefetch: ${AMAZON_SQS_NUMBER_OF_MESSAGES_TO_PREFETCH:5}
#    extended:
#      s3BucketName: ${AWS_SQS_EXT_S3_BUCKET_NAME}

#cloud.aws.stack.auto: false
#cloud.aws.region.static: us-east-1