version: '3.3'
services:
  fluentd:
      image: ascent/fluentd
      build:
          context: ../../fluentd
      ports:
          - 24224:24224
      networks:
          - logging
networks:
  logging:
    driver: bridge
  ascentnet:
    driver: bridge

