version: '3.3'
services:
  fluentd:
      image: ascent/fluentd
      build:
          context: ../
      environment:
          - SECURE_CONNECT=false
          - VAULT_TOKEN=vaultroot
          - VAULT_ADDR=http://vault:8200
      ports:
          - 24224:24224
      networks:
          - logging
networks:
  logging:
    driver: bridge
  ascentnet:
    driver: bridge

