version: '3.3'
services:
  vault:
    image: ascent/ascent-vault
    build: .. 
    hostname: vault
    cap_add:
      - IPC_LOCK
    environment:
      - SKIP_SETCAP=$SKIP_SETCAP
      - VAULT_ADDR=http://vault:8200
      - VAULT_DEV_ROOT_TOKEN_ID=vaultroot
      - VAULT_SECRETS_FILE=$VAULT_SECRETS_FILE
      - tls_disable=1
      - GIT_ACCESS_TOKEN=$GIT_ACCESS_TOKEN
    volumes:
      - ../config:/config
    ports:
      - "8200:8200"
    command: server -dev #-config /config/vault.conf
    networks:
        - ascentnet
        - logging
networks:
  ascentnet:
    driver: bridge
  logging:
    driver: bridge
