all: 
  - ../containers/vault
  - ../containers/elasticsearch
  - ../containers/fluentd
  - ../containers/kibana
  - ../containers/redis-sentinel
  - ../containers/rabbitmq
allservices:
  - ../../../ascent-config
  - ../../../ascent-dashboard
  - ../../../ascent-gateway
  - ../../../ascent-discovery
  - ../../../ascent-zipkin
localint:
  - ../containers/rabbitmq
  - ../containers/redis-sentinel
logging:
  - ../containers/elasticsearch
  - ../containers/kibana
  - ../containers/fluentd
sonarqube:
  - ../containers/sonarqube
