version: "3.3"
services:
    kibana:
        image: docker.elastic.co/kibana/kibana:6.0.0
        environment:
            - elasticsearch.url=http://elastic.internal.vets-api.gov:9200
            - xpack.security.enabled=false
            - xpack.monitoring.ui.container.elasticsearch.enabled=false
            - server.host="0.0.0.0/0"
        ports:
            - 5601:5601
        networks:
            logging:
                aliases:
                    - kibana.internal.vets-api.gov
            ascentnet:
                aliases:
                    - kibana.internal.vets-api.gov
        logging:
            driver: fluentd
            options:
                fluentd-async-connect: "true"
                fluentd-max-retries: "10"
                fluentd-retry-wait: "30s"
networks:
  logging:
    driver: bridge
  ascentnet:
    driver: bridge

