#Overrides for local development.
version: '3.3'

services:
    elastic.internal.vets-api.gov:
        build:
            context: ./elasticsearch
        environment:  
            - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
            - VAULT_TOKEN=
            - VAULT_ADDR=
            - SECURE_CONNECT=true
    es-config:
        build:
           context: ./es-config
        environment:  
            - VAULT_TOKEN=
            - VAULT_ADDR=
            - SECURE_CONNECT=true
    kibana.internal.vets-api.gov:
        build:
            context: ./kibana   
        environment:  
            - VAULT_TOKEN=
            - VAULT_ADDR=
            - SECURE_CONNECT=true
    fluentd:
        build:
            context: ./fluentd
        environment:  
             - SECURE_CONNECT=true
  ascentnet:
    driver: bridge
  logging:
    driver: bridge
