version: '3'
services:
  vault:
    image: vault
    hostname: vault
    cap_add:
      - IPC_LOCK
    environment:
      - SKIP_SETCAP=$SKIP_SETCAP
      - VAULT_ADDR=$VAULT_ADDR 
    volumes:
      - ./vault/config:/config
    ports:
      - "8200:8200"
    command: server -config /config/vault.conf
    networks:
        - ascentnet
networks:
  ascentnet:
    driver: overlay

