#Overrides for local development.
version: '3.3'

services:
    elasticsearch:
        build:
            context: ./elasticsearch
        environment:  
            - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
            - VAULT_TOKEN=
            - VAULT_ADDR=
    kibana:
        build:
            context: ./kibana   
        environment: 
            - VAULT_TOKEN=
            - VAULT_ADDR=
    fluentd:
        build:
            context: ./fluentd
    es-config:
        build:
            context: ./es-config

networks:
  ascentnet:
    driver: bridge
  logging:
    driver: bridge
