version: '3'

services:
  redis-master:
    image: redis:4.0.2-alpine
    command: redis-server --appendonly no --save "" --repl-diskless-sync yes --requirepass "${REDIS_PASSWORD}" --masterauth "${REDIS_PASSWORD}"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == master
    networks:
      - ascentnet
  # Slave
  redis-slave:
    image: redis:4.0.2-alpine
    command: redis-server --slaveof redis-master 6379 --appendonly no --repl-diskless-sync yes --requirepass "${REDIS_PASSWORD}" --masterauth "${REDIS_PASSWORD}"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == slave
    networks:
      - ascentnet
  redis-sentinel:
    image: ascent/redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - SENTINEL_PASSWORD=${REDIS_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - ascentnet
    depends_on:
      - redis-master
  redis-sentinel2:
    image: ascent/redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - SENTINEL_PASSWORD=${REDIS_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - ascentnet
    depends_on:
      - redis-master
  redis-sentinel3:
    image: ascent/redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - SENTINEL_PASSWORD=${REDIS_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - ascentnet
    depends_on:
      - redis-master
networks:
  ascentnet:
    driver: overlay
