#Overrides for local development.
version: '3'

services:
  redis-master:
    build:
      context: ./redis-sentinel
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
  redis-slave:
    build:
      context: ./redis-sentinel
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
  redis-sentinel:
    build:
      context: ./redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
  redis-sentinel2:
    build:
      context: ./redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
  redis-sentinel3:
    build:
      context: ./redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
networks:
    ascentnet:
        driver: bridge
    logging:
        driver: bridge
