version: '3'
services:
  ascent-amqp:
    image: rabbitmq
    hostname: ascent-amqp
    networks:
        - ascentnet
  ascent-discovery:
    image: jluck/ascent-discovery
    hostname: ascent-discovery
    ports:
     - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://$DISCOVERY_USERNAME:$DISCOVERY_PASSWORD@localhost:8761"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 5
    networks:
        - ascentnet
  ascent-config: 
    image: jluck/ascent-config
    hostname: ascent-config
    ports:
     - "8760:8760"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost:8760/info"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 5
    depends_on:
      - ascent-discovery
    networks:
        - ascentnet
  ascent-gateway:
    image: jluck/ascent-gateway
    hostname: ascent-gateway
    ports:
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    depends_on:
      - ascent-config
      - ascent-discovery
    networks:
        - ascentnet
  ascent-dashboard:
    image: jluck/ascent-dashboard
    hostname: ascent-dashboard
    ports:
     - "8763:8763"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    depends_on:
      - ascent-config
      - ascent-discovery
    networks:
        - ascentnet
  ascent-zipkin:
      image: jluck/ascent-zipkin
      hostname: ascent-zipkin
      ports:
       - "8700:8700"
      environment:
        - SPRING_PROFILES_ACTIVE=aws-prod
        - VAULT_ADDR=${VAULT_ADDR}
        - VAULT_TOKEN=${VAULT_TOKEN}      
      depends_on: 
        - ascent-discovery
        - ascent-config
      networks: 
        - ascentnet
        - logging 
networks:
  ascentnet:
    driver: overlay
  logging:
    driver: overlay
