version: '3.3'

services:
    #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
    elastic.internal.vets-api.gov:
        image: docker.io/ascent/ascent-elasticsearch
        container_name: elastic.internal.vets-api.gov
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - REPLICA_AMOUNT=1
            - MIN_MASTER_NODES=1 
        networks: 
            - logging
            - ascentnet
        ulimits:
            nproc: 655350
            nofile: 655350
            memlock:
                soft: -1
                hard: -1
        #TODO Add authentication to health check
        #healthcheck:
            #test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9200/_cat/health"]
            #timeout: 5s
        deploy:
            replicas: 3
            endpoint_mode: dnsrr
            placement:
                constraints: [node.role == worker]
            resources:
                reservations:
                    memory: 1536m

    es-config:
        image: docker.io/ascent/ascent-es-config
        container_name: es-config
        environment:
            - REPLICA_AMOUNT=1
        networks:
            - logging
        depends_on:
            - elastic.internal.vets-api.gov
        deploy:
            mode: global
            placement:
                constraints: [node.role == worker]

    fluentd:
        image: docker.io/ascent/fluentd
        container_name: fluentd
        ports:
            - 24224:24224
        networks:
            - logging
        depends_on:
            - elastic.internal.vets-api.gov
        deploy:
            mode: global
            placement:
                constraints: [node.role == worker]

    kibana.internal.vets-api.gov:
        image: docker.io/ascent/ascent-kibana
        container_name: kibana.internal.vets-api.gov
        ports: 
            - 5601:5601
        networks: 
            - logging
            - ascentnet
        depends_on: 
            - elastic.internal.vets-api.gov
        deploy:
            placement:
                constraints: [node.role == worker]
        logging:
            driver: fluentd
            options:
                fluentd-async-connect: "true"
                fluentd-max-retries: "10"
                fluentd-retry-wait: "30s"
networks:
  logging:
    driver: overlay
  ascentnet:
    driver: overlay

