#Overrides for local development.
version: '3'

services:
  redis-sentinel:
    build:
      context: ./redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
  redis-sentinel2:
    build:
      context: ./redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
  redis-sentinel3:
    build:
      context: ./redis-sentinel
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
networks:
    ascentnet:
        driver: bridge
    logging:
        driver: bridge
