version: '3'

services:
                
    redis-master:
      image: redis:4.0.2-alpine
      command: redis-server --appendonly no --save "" --repl-diskless-sync yes
      ports:
        - "6379:6379"
      deploy:
        mode: global
        placement:
          constraints:
            - node.hostname == ${REDIS_MASTER_HOSTNAME}
      networks: 
        - host
        - ascentnet
    # Slave
    redis-slave:
      image: redis:4.0.2-alpine
      command: redis-server --slaveof redis-master 6379 --appendonly no --repl-diskless-sync yes
      links:
        - redis-master
      environment:
        - REDIS_MASTER_HOST=${REDIS_MASTER_IP}
      deploy:
        mode: global
        placement:
          constraints:
            - node.hostname == ${REDIS_SLAVE_HOSTNAME}
      networks: 
        - host
        - ascentnet
    # Sentinel Instance 1
    redis-sentinel:
      build: 
        context: ./redis-sentinel
      links:
        - redis-master
      environment:
        - REDIS_MASTER_HOST=${REDIS_MASTER_IP}
        - SENTINEL_DOWN_AFTER=5000
        - SENTINEL_FAILOVER=15000
      deploy:
        mode: global
      networks: 
        - host
        - ascentnet
        
networks:
  host:
    driver: overlay
  ascentnet:
    driver: overlay