version: "3.3"
# original docker-compose file from 
# https://github.com/rabbitmq/rabbitmq-autocluster/tree/v3.6.x/examples/compose_consul_haproxy
# with some tweaks

services:
   rabbit:
    environment:
      - VAULT_TOKEN=vaultroot
      - VAULT_ADDR=http://vault:8200
      - TCP_PORTS=15672, 5672
      - AUTOCLUSTER_TYPE=consul
      - AUTOCLUSTER_DELAY=60
      - CONSUL_HOST=consul
      - CONSUL_SVC_ADDR_AUTO=true
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
      - CONSUL_DEREGISTER_AFTER=60 
    networks:
      - back
      - ascentnet
    build:
      context: ./rabbitmq
    expose:
    # TODO: I don't think all need to be exposed
      - 15672
      - 5672
      - 5671
      - 15671
    tty: true
   lb:
    image: dockercloud/haproxy
    environment:
      - MODE=tcp
    links:
      - rabbit
    ports:
      # TESTING ONLY: remember to shut off because this connection should be in internal docker network
      - 8080:80
      - 15672:15672
      - 5672:5672
    networks:
      - back
      - ascentnet
   #Suppported discovery services: https://github.com/aweber/rabbitmq-autocluster/wiki
   consul1:
    image: "consul"
    container_name: "consul"
    hostname: "consul"
    ports:
    # TODO: Don't think all of these should be exposed, either
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - back
      
networks:
  back:
    driver: bridge
  ascentnet:
    driver: bridge
