version: "3.3"
services:
   ascent-amqp:
    environment:
      - VAULT_TOKEN=vaultroot
      - VAULT_ADDR=http://vault:8200
      - TCP_PORTS=15672, 5672
      - AUTOCLUSTER_TYPE=consul
      - AUTOCLUSTER_DELAY=60
      - CONSUL_HOST=consul
      - CONSUL_SVC_ADDR_AUTO=true
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
      - CONSUL_DEREGISTER_AFTER=60 
    networks:
      back:
        aliases:
          - rabbit
      ascentnet:
        aliases:
          - rabbit
    build:
      context: ./rabbitmq
    expose:
      - 15672
      - 5672
      - 5671
      - 15671
    tty: true
#    command:  sh -c "sleep 20; rabbitmq-server;" 
   #https://github.com/docker/dockercloud-haproxy
   lb:
    image: dockercloud/haproxy
    environment:
      - MODE=tcp
    links:
      - ascent-amqp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # TESTING ONLY: remember to shut off because this connection should be in internal docker network
      - 8080:80
      - 15672:15672
      - 5672:5672
    networks:
      - back
      - ascentnet
   consul1:
    image: "consul"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - back
      
networks:
  back:
    driver: bridge
  ascentnet:
    driver: bridge
