version: '3'

services:

    #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
    elasticsearch:
        image: docker.io/ascent/ascent-elasticsearch
        networks: 
            - logging
            - ascentnet
        ulimits:
            nproc: 655350
            nofile: 655350
            memlock:
                soft: -1
                hard: -1
        #TODO Add authentication to health check
        #healthcheck:
            #test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9200/_cat/health"]
            #timeout: 5s
        deploy:
            placement:
                constraints: [node.role == worker]
            resources:
                reservations:
                    memory: 1536m

    fluentd:
        image: ascent/fluentd
        ports:
            - 24224:24224
        networks:
            - logging
        depends_on:
            - elasticsearch
        deploy:
            mode: global
            placement:
                constraints: [node.role == worker]

    kibana:
        image: docker.io/ascent/ascent-kibana
        ports: 
            - 5601:5601
        networks: 
            - logging
            - ascentnet
        depends_on: 
            - elasticsearch
        labels:
            gov.va.ascent.component: "logging"
        logging:
            driver: fluentd
            options:
                labels: "gov.va.ascent.component"
                fluentd-async-connect: "true"
                fluentd-max-retries: "10"
                fluentd-retry-wait: "30s"
        deploy:
            placement:
                constraints: [node.role == worker]
            
        
networks:
  logging:
    driver: overlay
  ascentnet:
    driver: overlay

