version: "3.3"
services:
   ascent-amqp:
    environment:
      - VAULT_TOKEN=vaultroot
      - VAULT_ADDR=http://vault:8200
    networks:
      back:
        aliases:
          - rabbit
      ascentnet:
        aliases:
          - rabbit
    build:
      context: ./rabbitmq
    expose:
      - 15672
      - 5672
      - 5671
      - 15671
    tty: true
    command:  sh -c "sleep 20; rabbitmq-server;" 
   #https://github.com/docker/dockercloud-haproxy
   consul1:
    image: consul:1.0.2
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - back
      
networks:
  back:
    driver: bridge
  ascentnet:
    driver: bridge
