#Overrides for local development.
version: '3'

services:
    filebeat:
        build:
            context: ./filebeat
        # Enable to turn on filebeat debugging
        #command: ["filebeat", "-e", "-d", "publish"]
        environment: 
            - VAULT_TOKEN=$VAULT_TOKEN
            - VAULT_ADDR=$VAULT_ADDR
    logstash:
        build:
            context: ./logstash
        environment: 
            - VAULT_TOKEN=$VAULT_TOKEN
            - VAULT_ADDR=$VAULT_ADDR
    
    elasticsearch:
        build:
            context: ./elasticsearch
        environment: 
            - VAULT_TOKEN=$VAULT_TOKEN
            - VAULT_ADDR=$VAULT_ADDR
    
    vault:
        image: vault
        networks: 
            - logging
        ports: 
            - 8200:8200
        environment:
            - VAULT_DEV_ROOT_TOKENID=vaultroot
        cap_add:
            - IPC_LOCK

networks:
  logging:
    driver: bridge
