version: '3'

services:

    #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
    elasticsearch:
        image: docker.io/jluck/ascent-elasticsearch
        networks: 
            - logging
        ulimits:
            nproc: 655350
            nofile: 655350
            memlock:
                soft: -1
                hard: -1
        #TODO Add authentication to health check
        #healthcheck:
            #test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9200/_cat/health"]
            #timeout: 5s
        deploy:
            placement:
                constraints: [node.role == worker]
            resources:
                reservations:
                    memory: 1536m

    filebeat:
        image: docker.io/jluck/ascent-filebeat
        volumes:
            - "/var/lib/docker-latest/containers:/dockerlogs:ro"
        networks: 
            - logging
        depends_on:
            - logstash
        deploy:
            mode: global
    
    logstash:
        image: docker.io/jluck/ascent-logstash
        networks: 
            - logging
        depends_on:
            - elasticsearch
        deploy:
            placement:
                constraints: [node.role == worker]

    kibana:
        image: docker.io/jluck/ascent-kibana
        ports: 
            - 5601:5601
        networks: 
            - logging
        depends_on: 
            - elasticsearch
        labels:
            gov.va.ascent.component: "logging"
        logging:
            driver: json-file
            options:
                labels: "gov.va.ascent.component"
        deploy:
            placement:
                constraints: [node.role == worker]
            
        
networks:
  logging:
    driver: overlay
