#Overrides for local development.
version: '3.3'

services:
    elastic.internal.vets-api.gov:
        build:
            context: ./elasticsearch
        environment:  
            - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
            - VAULT_TOKEN=
            - VAULT_ADDR=
    es-config:
        build:
           context: ./es-config
    kibana.internal.vets-api.gov:
        build:
            context: ./kibana   
        environment: 
            - VAULT_TOKEN=
            - VAULT_ADDR=
    fluentd:
        build:
            context: ./fluentd

networks:
  ascentnet:
    driver: bridge
  logging:
    driver: bridge
