version: '3.3'

services:
  ascent-amqp:
    build:
      context: ./rabbitmq
    environment:
      - VAULT_TOKEN=vaultroot
      - VAULT_ADDR=http://vault:8200
    ports:
      - 15672:15672
    networks:
        - ascentnet
networks:
  ascentnet:
    driver: bridge
