#Overrides for local development.
version: '3'

services:
    elasticsearch:
        build:
            context: ./elasticsearch
        environment: 
            - VAULT_TOKEN=
            - VAULT_ADDR=
            - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
        ports:
            - 9200:9200

    kibana:
        build:
            context: ./kibana
        environment: 
            - VAULT_TOKEN=
            - VAULT_ADDR=

    fluentd:
        build:
            context: ./fluentd

networks:
  ascentnet:
    driver: bridge
  logging:
    driver: bridge
