version: '3.3'

services:
    #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
    elasticsearch:
        image: ascent/ascent-elasticsearch
        container_name: elasticsearch
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - REPLICA_AMOUNT=1
            - MIN_MASTER_NODES=1 
        networks: 
            - logging
            - ascentnet
        ulimits:
            nproc: 655350
            nofile: 655350
            memlock:
                soft: -1
                hard: -1
        #TODO Add authentication to health check
        #healthcheck:
            #test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9200/_cat/health"]
            #timeout: 5s
        deploy:
            replicas: 3
            endpoint_mode: dnsrr
            placement:
                constraints: [node.role == worker]
            resources:
                reservations:
                    memory: 1536m

    es-config:
        image: ascent/ascent-es-config
        container_name: es-config
        networks:
            - logging
        depends_on:
            - elasticsearch
        deploy:
            mode: global
            placement:
                constraints: [node.role == worker] 


    fluentd:
        image: ascent/fluentd
        ports:
            - 24224:24224
        networks:
            - logging
        depends_on:
            - elasticsearch
        deploy:
            mode: global
            placement:
                constraints: [node.role == worker]

    kibana:
        image: docker.io/ascent/ascent-kibana
        ports: 
            - 5601:5601
        networks: 
            - logging
            - ascentnet
        depends_on: 
            - elasticsearch
        deploy:
            placement:
                constraints: [node.role == worker]
            
        
networks:
  logging:
    driver: overlay
  ascentnet:
    driver: overlay

