#Overrides for local development.
version: '3'

services:
    elasticsearch:
        build:
            context: ./elasticsearch
        environment:  
            - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
            - VAULT_TOKEN=
            - VAULT_ADDR=
        ports:
            - 9200:9200
    elasticsearch2:
        build:
            context: ./elasticsearch
        environment:  
            - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
            - VAULT_TOKEN=
            - VAULT_ADDR=
    elasticsearch3:
        build:
            context: ./elasticsearch
        environment:  
            - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
            - VAULT_TOKEN=
            - VAULT_ADDR=
    es-config:
        build:
            context: ./es-config
        environment:
            - VAULT_TOKEN=
            - VAULT_ADDR=
    kibana:
        build:
            context: ./kibana
        logging:
            driver: fluentd
            options:
                fluentd-async-connect: "true"
                fluentd-max-retries: "10"
                fluentd-retry-wait: "30s"    
        environment: 
            - VAULT_TOKEN=
            - VAULT_ADDR=
    fluentd:
        build:
            context: ./fluentd

networks:
  ascentnet:
    driver: bridge
  logging:
    driver: bridge
