version: '3'
services:
  ascent-amqp:
    image: rabbitmq
    hostname: ascent-amqp
    networks:
        - ascentnet
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
  ascent-discovery:
    image: ascent/ascent-discovery
    hostname: ascent-discovery
    ports:
     - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    networks:
        - ascentnet
  ascent-discovery-peer:
    image: ascent/ascent-discovery
    hostname: ascent-discovery-peer
    ports:
     - "8861:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    depends_on:
      - ascent-discovery
    networks:
        - ascentnet
  ascent-config: 
    image: ascent/ascent-config
    ports:
     - "8760:8760"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=https://${VAULT_HOST}:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_HOST=${VAULT_HOST}
      - VAULT_SCHEME=https
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    depends_on:
      - ascent-discovery
    networks:
        - ascentnet
  ascent-gateway:
    image: ascent/ascent-gateway
    ports:
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    depends_on:
      - ascent-config
      - ascent-discovery
    networks:
        - ascentnet
  ascent-dashboard:
    image: ascent/ascent-dashboard
    ports:
     - "8763:8763"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    depends_on:
      - ascent-config
      - ascent-discovery
    networks:
        - ascentnet
  ascent-zipkin:
    image: ascent/ascent-zipkin
    ports:
      - "8700:8700"
    environment:
      - SPRING_PROFILES_ACTIVE=aws-prod
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN} 
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"     
    depends_on: 
      - ascent-discovery
      - ascent-config
    networks: 
      - ascentnet
      - logging 
networks:
  ascentnet:
    driver: overlay
  logging:
    driver: overlay