#Overrides for local development.
version: '3.3'

services:
    elasticsearch:
        build:
            context: ./elasticsearch
        environment:  
            - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
            - VAULT_TOKEN=vaultroot
            - VAULT_ADDR=http://vault:8200
            - SECURE_CONNECT=true
        ports:
            - 9200:9200
    es-config:
        build:
           context: ./es-config
        environment:  
            - VAULT_TOKEN=vaultroot
            - VAULT_ADDR=http://vault:8200
            - SECURE_CONNECT=true
    kibana:
        build:
            context: ./kibana   
        environment:  
            - VAULT_TOKEN=vaultroot
            - VAULT_ADDR=http://vault:8200
            - SECURE_CONNECT=true
    fluentd:
        build:
            context: ./fluentd
        environment:  
            - SECURE_CONNECT=true
            - VAULT_TOKEN=vaultroot
            - VAULT_ADDR=http://vault:8200
networks:
    ascentnet:
        driver: bridge
    logging:
        driver: bridge
